### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by mhoeher** [c0fec0de/git-ws#3]
We shall extend the user manual to include the most important information needed by new users to understand and use the tool.

- [x] Write page about the Manifest. -> @c0fec0de 
- [x] Write page about how the Dependency Resolution works. -> @mhoeher 
- [x] Write page about how the Group Filtering works.
- [x] Write page about how the Tagging is done.
- [x] Update Readme
- [x] Document non-main support (#44)
- [x] Review API doc ->  @c0fec0de

**Comment by c0fec0de** [comment]
done for now

**Comment by c0fec0de** [comment]
* [x] Group Filter Documentation on command line @c0fec0de 
* [x] Default Group Selection @mhoeher 
* [ ] Tips and Tricks
    * [ ] CI Setup
    * [ ] Deduplication vs. git-ws feature
    * [ ] Feature Branches

**Comment by c0fec0de** [comment]
Tips and Tricks are nice to have. 
Close for now.
