### ISSUE TITLE
Clarify/refine group filter selection

### ISSUE THREAD

**Issue by mhoeher** [c0fec0de/git-ws#8]
Currently, we have the following for the group filter/selection:

```
## Groups are optional by default.
## If a dependency belongs to a group, it becomes optional likewise.
## Groups can be later on selected/deselected by '+group' or '-group'.
## An optional group can be selected by '+group',
## a non-optional group can be deselected by '-group'.
## Deselection has higher priority than selection.
```

This means that a filter like `+my_group,-my_group,+my_group` would result in `my_group` not being selected. This is a bit counter intuitive, especially when comparing the mechanism to other similar ones. For example, applications that consume options and especially flags often allow to set a flag via `--feature` and disable it via `--no-feature`. The arguments are evaluated *in order* and and basically whatever appears last wins. This probably also makes more sense for the filtering (especially in cases where users might generate the filter expression from something else).

**Comment by c0fec0de** [comment]
## New Concept
* General Idea: Package-like dependency management
  * all groups of a package are installed by default, if the package is the top package
  * all groups of a package are **NOT** installed by default, if the the package is a dependency
* A dependency can belong to any number of groups
```toml
[[dependencies]]
name = 'test'
groups = ['groupA', 'groupB']
```
* Groups of a dependency must be explicitly selected (i.e. a feature which is available)
Assume the following dependency `dep/git-ws.toml`:
```toml
# Feature needs a special dependency
[[dependencies]]
name = 'dep-dep'
groups = ['feature']
```
Main Project `main/git-ws.toml`: 
```toml
[[dependencies]]
name = 'dep'
with-groups = ['feature']
```

## Changes

- [x] Adapt `Filter`
- [x] Adapt `groups` on `Project` and `ProjectSpec`
- [x] Add `with-groups` on `Project` and `ProjectSpec`
- [x] Remove `groups` from `Manifest` and `ManifestSpec`
- [x] Remove `Group`
- [x] Add  `groups-filter` to `Manifest` and `ManifestSpec`
- [x] Adapt group filter on API and command line (highest-prio)
- [x] Implement `groups-filter`
  * manifest (lowest-prio)
  * config (mid-prio)
  * command line (highest-prio)
* final group filter settings are created by just concat the three locations from above
* Syntax: `+group, -group, +group@path, -group@path`
* Dep is only deact if all groups are deact
