### ISSUE TITLE
Discussion: Migration to PDM

### ISSUE THREAD

**Issue by mhoeher** [c0fec0de/git-ws#85]
I recently learned about [PDM](https://github.com/pdm-project/pdm), an alternative Python package manager that does a pretty similar job to Poetry.

The main difference is, that PDM closely follows the standard PEPs (particularly, [PEP 261](https://peps.python.org/pep-0621/)), while poetry stores such information in an own section.

/cc @c0fec0de

**Comment by c0fec0de** [comment]
Let's try out

**Comment by c0fec0de** [comment]
Let's also check, what other projects like scipy, pandas, ... are using

**Comment by cmarqu** [comment]
If you don't use poetry plugins, you should be fine; if you do, it depends on the plugin. :)

One smallish thing is that Dependabot doesn't yet support PDM (https://github.com/dependabot/dependabot-core/issues/3190).
