### ISSUE TITLE
Switch to ruff

### ISSUE THREAD

**Issue by c0fec0de** [c0fec0de/git-ws#86]
Use https://pypi.org/project/ruff/ as linter
* [x] Determine settings
* [x] Fix finding
* [ ] Add pre-commit hook

**Comment by cmarqu** [comment]
FWIW, we replaced flake8, isort (I thought, but it needs to be enabled explicitly which I forgot in the PR) and black with ruff and ruff-format recently in cocotb: https://github.com/cocotb/cocotb/pull/3499.

You might also want to have the changes in https://github.com/cocotb/cocotb/pull/3520/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R49-R53

**Comment by c0fec0de** [comment]
Very good pointer. Thanks.
